export const INIT_SOCKET = 'INIT_SOCKET';
export const SET_STATE_FROM_SOCKET = 'SET_STATE_FROM_SOCKET';
export const SELECT_CONVERSATION = 'SELECT_CONVERSATION';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const ADD_CONVERSATION = 'ADD_CONVERSATION';
export const SET_USER_ID = 'SET_USER_ID';
